[city_coordinates]
"Москва"          = { lat = 55.7558, lon = 37.6173 }
"Санкт-Петербург" = { lat = 59.9343, lon = 30.3351 }
"Новосибирск"     = { lat = 55.0084, lon = 82.9357 }
"Екатеринбург"    = { lat = 56.8389, lon = 60.6057 }
"Казань"          = { lat = 55.7903, lon = 49.1347 }
"Нижний Новгород" = { lat = 56.2965, lon = 43.9361 }
"Челябинск"       = { lat = 55.1644, lon = 61.4368 }
"Самара"          = { lat = 53.2415, lon = 50.2212 }
"Омск"            = { lat = 54.9885, lon = 73.3242 }
"Ростов-на-Дону"  = { lat = 47.2357, lon = 39.7015 }
"Уфа"             = { lat = 54.7388, lon = 55.9721 }
"Красноярск"      = { lat = 56.0153, lon = 92.8932 }
"Пермь"           = { lat = 58.0104, lon = 56.2294 }
"Воронеж"         = { lat = 51.6615, lon = 39.2005 }
"Волгоград"       = { lat = 48.7080, lon = 44.5133 }
"Владивосток"     = { lat = 43.1155, lon = 131.885 }
